### ISSUE TITLE
BuyToCover: 585808 Market.. thats gunna get me a Margin call

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#34] opened 2020-12-09 20:09 UTC
The some images where from after the Sim Count dropped to zero.  

![image](https://user-images.githubusercontent.com/15313578/101681138-52aae880-3a27-11eb-8d2c-c10bde7ff9a7.png)

![image](https://user-images.githubusercontent.com/15313578/101680695-aec13d00-3a26-11eb-8209-a4435de3030e.png)

Order: Sell 32 Market
![image](https://user-images.githubusercontent.com/15313578/101680514-6f92ec00-3a26-11eb-9d46-64b79bfb5b53.png)

**Comment by jmscraig** [comment] 2020-12-09 20:12
I ran the MA cross with these settings on a 10tick dataset, through the strategy tab with no ES chart up. 

Same print() message error on launch

No orders ever appeared in the order window.

for a while showed a 4 contract position

quickly melted a brand new 100k sim account  Lol.

![image](https://user-images.githubusercontent.com/15313578/101681848-67d44700-3a28-11eb-9f04-49805112950f.png)

**Comment by jmscraig** [comment] 2020-12-09 20:22
[ATS.NT8.20201209.Trace .txt](https://github.com/MicroTrendsLtd/NinjaTrader8/files/5668465/ATS.NT8.20201209.Trace.txt)

**Comment by jmscraig** [comment] 2020-12-09 20:52
Rebooted and relaunched the same code with close to same * config through a chart and it launched fine.

----------------------------------------------------------------------
with close to same * config

I set Error Retrys to 12 instead of 15
I left time out a 10 instead of setting it to 12

Still used a 10tick data series but the chart lets me select only 200 bars and starting the strategy through the tab forced me to select a whole day

**Comment by jmscraig** [comment] 2020-12-09 20:53
So far is running on live data..  Showed no issues through the crazy volume minute 2:50pm.

**Comment by MicroTrendsTom** [comment] 2020-12-10 03:43
ok my tests on all went all fine no unhandled errors no lock ups or other -
Even with NT8 popups and a disconnect test - no exceptions or problems unexpected.
looking good for the ConcDict
Unable to reproduce the Print Error
Account cash i reset before each test

**Comment by MicroTrendsTom** [comment] 2020-12-10 03:46
ok my tests on all went all fine no unhandled errors no lock ups or other -
Even with NT8 popups and a disconnect test - no exceptions or problems unexpected.
looking good for the ConcDict
Unable to reproduce the Print Error
Account cash i reset before each test  - MNQ on 100K -   ES 1Mil etc

Money management - Min Cash needs to be added as a feature in a layer etc so we will close this  as expected behaviour 
its down to the trader to plan the correct trading capital versus the system at this point etc
and highlight that in the Backlog
https://github.com/MicroTrendsLtd/NinjaTrader8/issues/31#issue-759996352

**Closed by MicroTrendsTom** 2020-12-10 03:46 UTC
