### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by admintiger** [MicroTrendsLtd/NinjaTrader8#40] opened 2021-01-16 22:36 UTC
Hi, I was pleasantly surprised to find this project back in November when it had become overwhelmingly obvious during NT strategy development and testing that unmanaged mode has to be used to have much hope of routinely making money, and that the provided NT framework isn't robust enough to run unsupervised day and night without potentially-devastating losses due order-rejections, overfills, and other conditions that halt processing and leave uncontrollable open orders and market positions. I understand jmscraig took time away from this to celebrate his son's graduation, but it has been quite a while since there has been a post and I am hoping the project isn't dead. If not, I am looking forward to some testing.

**Comment by MicroTrendsTom** [comment] 2021-01-17 12:40
@jmscraig collaborated on some locking techniques and objects   -after his testing found some lockups. Which i was not able to reproduce until i performed some regression testing on a 1 second reversals and low and behold found an issue introduced during a change,  and so that testing was very welcome and so was the input on locking   -etc.   locking was rolled back to a bare minimum. Going forwards we might indeed migrate to concurrent objects but there is no need currently.

I do have some components to add in such as  additional layers, trade manger guis, easy settings configuration components, and a layer that will provide off the shelf features such as overrides for signal entry, filter, exit logic - plus stops, stop trails, targets etc 

so not dead but the current layer is good enough as is.. but some polishing to remove the close using limit as that is not complete, and to close the issue as it cant be reproduced in millions of tests and with dozens of uses in beta for some products using this as the engine.

i will also add some of my favorite indicators and approaches i use for trading.

Currently writing large swathes of code and systems and will make some updates to this repos jan/feb etc

**Comment by MicroTrendsTom** [comment] 2021-01-17 12:47
out of interest i will be using this engine for the strategy version of this trading system
https://algofuturestrader.zendesk.com/hc/en-us/articles/360055568611-NinjaTrader-7-AFT7-day-trading-futures-system-overview-of-components

**Comment by admintiger** [comment] 2021-01-17 18:54
Great! Looking forward to your additional components and other updates.

**Closed** 2021-02-22 13:28 UTC
